name: Manage Review Labels

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'release-*'

jobs:
  label-on-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Manage LGTM Review Label
        uses: actions/github-script@v7
        with:
          script: |
            const LGTM_LABEL = 'lgtm';

            // Extract review details
            const { state: reviewState } = context.payload.review;
            const pullRequestNumber = context.payload.pull_request.number;
            const repoDetails = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber
            };

            // Log review information
            console.log(`Processing review for PR #${pullRequestNumber}`);
            console.log(`Review state: ${reviewState}`);

            // Helper function to check for LGTM label
            async function hasLgtmLabel() {
              const { data: labels } = await github.rest.issues.listLabelsOnIssue(repoDetails);
              return labels.some(label => label.name === LGTM_LABEL);
            }

            if (reviewState === 'approved') {
              const lgtmExists = await hasLgtmLabel();

              if (!lgtmExists) {
                console.log(`Adding ${LGTM_LABEL} label to PR #${pullRequestNumber}`);
                await github.rest.issues.addLabels({
                  ...repoDetails,
                  labels: [LGTM_LABEL]
                });
                console.log('Label added successfully');
              } else {
                console.log(`${LGTM_LABEL} label already exists`);
              }
            } else if (reviewState === 'changes_requested') {
              const lgtmExists = await hasLgtmLabel();

              if (lgtmExists) {
                console.log(`Removing ${LGTM_LABEL} label from PR #${pullRequestNumber}`);
                await github.rest.issues.removeLabel({
                  ...repoDetails,
                  name: LGTM_LABEL
                });
                console.log('Label removed successfully');
              } else {
                console.log(`No ${LGTM_LABEL} label to remove`);
              }
            }

  label-rc-prs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && startsWith(github.base_ref, 'release-')
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Auto-label RC PRs with type:release
        uses: actions/github-script@v7
        with:
          script: |
            const RELEASE_LABEL = 'type:release';
            const pullRequestNumber = context.payload.pull_request.number;
            const repoDetails = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber
            };

            console.log(`Auto-labeling RC PR #${pullRequestNumber} with ${RELEASE_LABEL}`);
            console.log(`Target branch: ${context.payload.pull_request.base.ref}`);

            // Check if the label already exists
            const { data: labels } = await github.rest.issues.listLabelsOnIssue(repoDetails);
            const hasReleaseLabel = labels.some(label => label.name === RELEASE_LABEL);

            if (!hasReleaseLabel) {
              console.log(`Adding ${RELEASE_LABEL} label to RC PR #${pullRequestNumber}`);
              await github.rest.issues.addLabels({
                ...repoDetails,
                labels: [RELEASE_LABEL]
              });
              console.log('Release label added successfully');
            } else {
              console.log(`${RELEASE_LABEL} label already exists`);
            }
